import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
import { RouteEndpoint } from './extractor.js';

const HTTP_METHODS = new Set(['GET', 'POST', 'PUT', 'DELETE', 'PATCH']);

/**
 * Extracts Express route declarations (e.g. router.get('/path', ...)) from a source file using AST.
 */
export function extractRoutesFromFile(filePath: string): RouteEndpoint[] {
  if (!fs.existsSync(filePath)) return [];

  const content = fs.readFileSync(filePath, 'utf-8');
  let scriptKind = ts.ScriptKind.TS;
  if (filePath.endsWith('.js')) scriptKind = ts.ScriptKind.JS;

  const sourceFile = ts.createSourceFile(
    filePath,
    content,
    ts.ScriptTarget.Latest,
    true,
    scriptKind
  );

  const routes: RouteEndpoint[] = [];

  function visit(node: ts.Node) {
    if (ts.isCallExpression(node)) {
      if (ts.isPropertyAccessExpression(node.expression)) {
        const methodName = node.expression.name.text.toUpperCase();
        if (HTTP_METHODS.has(methodName) && node.arguments.length >= 1) {
          const firstArg = node.arguments[0];
          let routePath = '';

          if (ts.isStringLiteral(firstArg)) {
            routePath = firstArg.text;
          } else if (ts.isNoSubstitutionTemplateLiteral(firstArg)) {
            routePath = firstArg.text;
          }

          if (routePath) {
            let schema: string | undefined;
            let handler: string | undefined;

            // Check middle arguments for validate(Schema) or handlers
            for (let i = 1; i < node.arguments.length; i++) {
              const arg = node.arguments[i];

              // e.g. validate(CreateUserSchema)
              if (ts.isCallExpression(arg) && arg.arguments.length > 0) {
                const subArg = arg.arguments[0];
                if (ts.isIdentifier(subArg)) {
                  schema = subArg.text;
                }
              }

              // e.g. userController.createUser or handleCreate
              if (ts.isPropertyAccessExpression(arg)) {
                handler = `${arg.expression.getText(sourceFile)}.${arg.name.text}`;
              } else if (ts.isIdentifier(arg) && !schema) {
                handler = arg.text;
              }
            }

            // Extract JSDoc comment if present on parent statement
            let description: string | undefined;
            const parentStatement = node.parent;
            if (parentStatement) {
              const text = sourceFile.getFullText();
              const ranges = ts.getLeadingCommentRanges(text, parentStatement.getFullStart());
              if (ranges && ranges.length > 0) {
                const commentText = text.slice(ranges[0].pos, ranges[0].end);
                description = commentText
                  .replace(/^\/\*\*?|\*\/$/g, '')
                  .split('\n')
                  .map((l) => l.replace(/^\s*\*\s?/, '').trim())
                  .filter(Boolean)
                  .join(' ');
              }
            }

            routes.push({
              method: methodName as any,
              path: routePath,
              schema,
              handler,
              description,
            });
          }
        }
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return routes;
}

/**
 * Generates an ambient TypeScript type contract file (.context/contracts.d.ts)
 * bridging Client fetchers with Server Express routes.
 */
export function generateContractsDeclaration(routes: RouteEndpoint[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED BY ARCHON FULLSTACK CONTRACT LINKER',
    '// DO NOT EDIT DIRECTLY. Real-time synchronized Client <-> Server Type Contracts.',
    '',
    'export interface ArchonApiEndpoints {',
  ];

  if (routes.length === 0) {
    lines.push('  // No server routes detected yet');
  } else {
    for (const r of routes) {
      const key = `"${r.method} ${r.path}"`;
      const schemaType = r.schema ? `${r.schema}Input` : 'unknown';
      lines.push(`  /**`);
      if (r.description) lines.push(`   * ${r.description}`);
      if (r.handler) lines.push(`   * Handler: ${r.handler}`);
      lines.push(`   */`);
      lines.push(`  ${key}: {`);
      lines.push(`    body: ${r.method === 'GET' ? 'undefined' : schemaType};`);
      lines.push(`    response: unknown;`);
      lines.push(`  };`);
    }
  }

  lines.push('}');
  lines.push('');
  lines.push('export type ApiRouteKey = keyof ArchonApiEndpoints;');
  lines.push('');

  return lines.join('\n');
}
