import fs from 'node:fs';
import path from 'node:path';
import fg from 'fast-glob';
import { extractModuleExports, ModuleSkeleton, ProjectSkeleton, RouteEndpoint } from './extractor.js';
import { extractRoutesFromFile, generateContractsDeclaration } from './contract.js';

export interface GenerateSkeletonOptions {
  cwd?: string;
  outDir?: string;
  writeModuleSpecs?: boolean;
}

export function generateContextMapMarkdown(skeleton: ProjectSkeleton): string {
  const lines: string[] = [
    '# 🗺️ ARCHON ARCHITECTURAL CONTEXT MAP',
    '<!-- AUTO-GENERATED BY ARCHON SKELETON. DO NOT EDIT DIRECTLY. -->',
    '<!-- Single Source of Truth for AI Agents (Gemini, Claude, Cursor, Windsurf) -->',
    `<!-- Last Updated: ${skeleton.generatedAt} -->`,
    '',
    '> [!IMPORTANT]',
    '> **AI AGENT MANDATE:**',
    '> 1. **Check this map first** before writing any new function, endpoint, or utility.',
    '> 2. **Reuse existing functions** listed below. DO NOT re-implement duplicate utilities.',
    '> 3. **Never deep import**: Import across modules ONLY via `@/modules/[moduleName]`.',
    '> 4. Add JSDoc comments (`/** ... */`) to any new exported function so Archon can index it.',
    '',
  ];

  const clientModules = skeleton.modules.filter((m) => m.side === 'client');
  const serverModules = skeleton.modules.filter((m) => m.side === 'server');

  // 1. Client Modules Section
  if (clientModules.length > 0) {
    lines.push('## 🖥️ CLIENT MODULES (`client/src/modules/`)');
    lines.push('');
    for (const mod of clientModules) {
      lines.push(`### 📦 \`@/modules/${mod.moduleName}\``);
      lines.push(`- **Gateway:** \`${mod.gatewayPath}\``);
      if (mod.internalFiles.length > 0) {
        lines.push(`- **Internal Files:** \`${mod.internalFiles.join('`, `')}\``);
      }
      lines.push('');

      const functions = mod.exports.filter((e) => e.kind === 'function');
      const components = mod.exports.filter((e) => e.kind === 'component');
      const types = mod.exports.filter((e) => e.kind === 'interface' || e.kind === 'type');
      const variables = mod.exports.filter((e) => e.kind === 'variable');
      const reexports = mod.exports.filter((e) => e.kind === 'reexport');

      if (components.length > 0) {
        lines.push('**UI Components:**');
        for (const comp of components) {
          lines.push(`- 🎨 \`<${comp.name} />\` \`${comp.signature || ''}\``);
          if (comp.description) lines.push(`  > *${comp.description}*`);
        }
        lines.push('');
      }

      if (functions.length > 0) {
        lines.push('**Public Functions:**');
        for (const fn of functions) {
          lines.push(`- ⚡ \`${fn.name}${fn.signature || '()'}\``);
          if (fn.description) lines.push(`  > *${fn.description}*`);
        }
        lines.push('');
      }

      if (types.length > 0) {
        lines.push('**Types & Interfaces:**');
        for (const t of types) {
          lines.push(`- 📄 \`${t.kind} ${t.name}\``);
          if (t.description) lines.push(`  > *${t.description}*`);
        }
        lines.push('');
      }

      if (variables.length > 0) {
        lines.push('**Schemas & Constants:**');
        for (const v of variables) {
          lines.push(`- 🛡️ \`${v.name}: ${v.signature}\``);
          if (v.description) lines.push(`  > *${v.description}*`);
        }
        lines.push('');
      }

      if (reexports.length > 0) {
        lines.push('**Other Re-exports:**');
        for (const r of reexports) {
          lines.push(`- 🔗 \`${r.name} ${r.signature || ''}\``);
        }
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    }
  }

  // 2. Server Modules Section
  if (serverModules.length > 0) {
    lines.push('## ⚙️ SERVER MODULES (`server/src/modules/`)');
    lines.push('');
    for (const mod of serverModules) {
      lines.push(`### 📦 \`@/modules/${mod.moduleName}\``);
      lines.push(`- **Gateway:** \`${mod.gatewayPath}\``);
      if (mod.internalFiles.length > 0) {
        lines.push(`- **Internal Files:** \`${mod.internalFiles.join('`, `')}\``);
      }
      lines.push('');

      const functions = mod.exports.filter((e) => e.kind === 'function');
      const types = mod.exports.filter((e) => e.kind === 'interface' || e.kind === 'type');
      const variables = mod.exports.filter((e) => e.kind === 'variable');
      const reexports = mod.exports.filter((e) => e.kind === 'reexport');

      if (functions.length > 0) {
        lines.push('**Public Functions & Handlers:**');
        for (const fn of functions) {
          lines.push(`- ⚡ \`${fn.name}${fn.signature || '()'}\``);
          if (fn.description) lines.push(`  > *${fn.description}*`);
        }
        lines.push('');
      }

      if (types.length > 0) {
        lines.push('**Types & Interfaces:**');
        for (const t of types) {
          lines.push(`- 📄 \`${t.kind} ${t.name}\``);
          if (t.description) lines.push(`  > *${t.description}*`);
        }
        lines.push('');
      }

      if (variables.length > 0) {
        lines.push('**Routes, Schemas & Constants:**');
        for (const v of variables) {
          lines.push(`- 🛡️ \`${v.name}: ${v.signature}\``);
          if (v.description) lines.push(`  > *${v.description}*`);
        }
        lines.push('');
      }

      if (mod.routes && mod.routes.length > 0) {
        lines.push('**🌐 Express API Endpoints:**');
        for (const r of mod.routes) {
          const schemaInfo = r.schema ? ` (Body: \`${r.schema}\`)` : '';
          const handlerInfo = r.handler ? ` ➔ \`${r.handler}\`` : '';
          lines.push(`- 🚀 \`${r.method} ${r.path}\`${schemaInfo}${handlerInfo}`);
          if (r.description) lines.push(`  > *${r.description}*`);
        }
        lines.push('');
      }

      if (reexports.length > 0) {
        lines.push('**Other Re-exports:**');
        for (const r of reexports) {
          lines.push(`- 🔗 \`${r.name} ${r.signature || ''}\``);
        }
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    }
  }

  return lines.join('\n');
}

export function generateModuleSpecMarkdown(mod: ModuleSkeleton): string {
  const lines: string[] = [
    `# Module Specification: \`${mod.moduleName}\` (${mod.side})`,
    `<!-- AUTO-GENERATED BY ARCHON. Public gateway: ${mod.gatewayPath} -->`,
    '',
    `## Public Gateway (\`index.ts\`)`,
    `Code outside this module MUST ONLY import from \`@/modules/${mod.moduleName}\`.`,
    '',
  ];

  if (mod.exports.length === 0) {
    lines.push('*No public exports yet.*');
  } else {
    for (const exp of mod.exports) {
      lines.push(`### \`${exp.kind.toUpperCase()}\` ${exp.name}`);
      if (exp.signature) lines.push(`\`\`\`ts\n${exp.name}${exp.signature}\n\`\`\``);
      if (exp.description) lines.push(`> ${exp.description}`);
      lines.push('');
    }
  }

  if (mod.internalFiles.length > 0) {
    lines.push('## Internal Module Files');
    for (const file of mod.internalFiles) {
      lines.push(`- \`${file}\``);
    }
  }

  return lines.join('\n');
}

export async function generateProjectSkeleton(
  options: GenerateSkeletonOptions = {}
): Promise<ProjectSkeleton> {
  const cwd = options.cwd || process.cwd();
  const outDir = options.outDir || path.resolve(cwd, '.context');

  const moduleSkeletons: ModuleSkeleton[] = [];

  // Helper to collect internal files of a module directory
  async function collectInternalFiles(modDir: string): Promise<string[]> {
    const files = await fg('**/*.{ts,tsx,js,jsx}', {
      cwd: path.resolve(cwd, modDir),
      ignore: ['index.*', '**/*.spec.*', '**/*.test.*'],
    });
    return files.map((f) => f.replace(/\\/g, '/'));
  }

  // 1. Scan client modules
  const clientGateways = await fg('client/src/modules/*/index.{ts,tsx,js,jsx}', { cwd });
  for (const gateway of clientGateways) {
    const normalized = gateway.replace(/\\/g, '/');
    const parts = normalized.split('/');
    const moduleName = parts[3];
    const modDir = `client/src/modules/${moduleName}`;
    const exports = extractModuleExports(path.resolve(cwd, gateway));
    const internalFiles = await collectInternalFiles(modDir);

    moduleSkeletons.push({
      moduleName,
      side: 'client',
      gatewayPath: normalized,
      exports,
      internalFiles,
    });
  }

  // 2. Scan server modules
  const serverGateways = await fg('server/src/modules/*/index.{ts,js}', { cwd });
  for (const gateway of serverGateways) {
    const normalized = gateway.replace(/\\/g, '/');
    const parts = normalized.split('/');
    const moduleName = parts[3];
    const modDir = `server/src/modules/${moduleName}`;
    const exports = extractModuleExports(path.resolve(cwd, gateway));
    const internalFiles = await collectInternalFiles(modDir);

    // Extract Express API routes in this module
    const routeFiles = await fg([`${modDir}/**/routes/**/*.{ts,js}`, `${modDir}/**/*route*.{ts,js}`, `${gateway}`], { cwd });
    const routes: RouteEndpoint[] = [];
    for (const rf of routeFiles) {
      const extracted = extractRoutesFromFile(path.resolve(cwd, rf));
      routes.push(...extracted);
    }

    moduleSkeletons.push({
      moduleName,
      side: 'server',
      gatewayPath: normalized,
      exports,
      internalFiles,
      routes,
    });
  }

  // 3. Scan root src/modules if exists
  const rootGateways = await fg('src/modules/*/index.{ts,tsx,js,jsx}', { cwd });
  for (const gateway of rootGateways) {
    const normalized = gateway.replace(/\\/g, '/');
    const parts = normalized.split('/');
    const moduleName = parts[2];
    const modDir = `src/modules/${moduleName}`;
    const exports = extractModuleExports(path.resolve(cwd, gateway));
    const internalFiles = await collectInternalFiles(modDir);

    moduleSkeletons.push({
      moduleName,
      side: 'client',
      gatewayPath: normalized,
      exports,
      internalFiles,
    });
  }

  const skeleton: ProjectSkeleton = {
    generatedAt: new Date().toISOString(),
    preset: 'vite-express-modular',
    modules: moduleSkeletons,
  };

  // Ensure output directory exists
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  // Write architecture.json
  const jsonPath = path.resolve(outDir, 'architecture.json');
  fs.writeFileSync(jsonPath, JSON.stringify(skeleton, null, 2), 'utf-8');

  // Write .context/MAP.md (Markdown Bible for AI Agents)
  const mapPath = path.resolve(outDir, 'MAP.md');
  const mapMarkdown = generateContextMapMarkdown(skeleton);
  fs.writeFileSync(mapPath, mapMarkdown, 'utf-8');

  // Write skeleton.d.ts for ultra-compact AI prompting & type declarations
  const dtsLines: string[] = [
    '// AUTO-GENERATED BY ARCHON SKELETON BUILDER',
    '// This file provides AI agents with instant architectural signatures and public gateways.',
    '',
  ];

  for (const mod of moduleSkeletons) {
    const alias = `@/modules/${mod.moduleName}`;
    dtsLines.push(`declare module '${alias}' {`);
    for (const exp of mod.exports) {
      if (exp.kind === 'function') {
        dtsLines.push(`  export function ${exp.name}${exp.signature};`);
      } else if (exp.kind === 'component') {
        dtsLines.push(`  export const ${exp.name}: (props: any) => any;`);
      } else if (exp.kind === 'variable') {
        dtsLines.push(`  export const ${exp.name}: ${exp.signature};`);
      } else if (exp.kind === 'type' || exp.kind === 'interface') {
        dtsLines.push(`  ${exp.signature}`);
      } else if (exp.kind === 'reexport') {
        dtsLines.push(`  export * ${exp.signature || ''};`);
      }
    }
    dtsLines.push('}');
    dtsLines.push('');
  }

  const dtsPath = path.resolve(outDir, 'skeleton.d.ts');
  fs.writeFileSync(dtsPath, dtsLines.join('\n'), 'utf-8');

  // Write contracts.d.ts (Fullstack TypeSafe API Bridge)
  const allRoutes = moduleSkeletons.flatMap((m) => m.routes || []);
  const contractsContent = generateContractsDeclaration(allRoutes);
  const contractsPath = path.resolve(outDir, 'contracts.d.ts');
  fs.writeFileSync(contractsPath, contractsContent, 'utf-8');

  // Optionally write SPEC.md inside each module folder
  if (options.writeModuleSpecs) {
    for (const mod of moduleSkeletons) {
      const moduleFolder = path.resolve(cwd, path.dirname(mod.gatewayPath));
      const specPath = path.resolve(moduleFolder, 'SPEC.md');
      const specContent = generateModuleSpecMarkdown(mod);
      fs.writeFileSync(specPath, specContent, 'utf-8');
    }
  }

  return skeleton;
}
